### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by vinniks29** [Sylpheo/nibs-ibeacon#1]
I am getting below error when run npm install command. Following are the versions i am using:

node v0.12.2
npm v2.7.4
Python 2.5.0

C:\Heroku\nibs-ibeacon>npm install
|

> bcrypt@0.7.8 install C:\nibs-ibeacon\node_modules\bcrypt
> node-gyp rebuild

C:\Heroku\nibs-ibeacon\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Softwares\nodejs\node_modules\npm\bin\node-gyp-bin\....\node
_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 11, in <module>
    import gyp
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Heroku\nibs-ibeacon\node_modules\bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
## npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})

> pg@2.11.1 install C:\Heroku\nibs-ibeacon\node_modules\pg
> node-gyp rebuild || (exit 0)

C:\Heroku\nibs-ibeacon\node_modules\pg>if not defined npm_config_node_gyp (node "C:\Softwares\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 11, in <module>
    import gyp
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Heroku\nibs-ibeacon\node_modules\pg
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Softwares\nodejs\\node.exe" "C:\Softwares\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

**Comment by jeancdc** [comment]
Downgrade your version of Node.js. Use the same of this project : 0.10.36. You can find it at http://blog.nodejs.org/2015/01/26/node-v0-10-36-stable/ or you can install it with [nvm](https://github.com/coreybutler/nvm-windows).
Also install first [PostgreSQL](http://www.enterprisedb.com/products-services-training/pgdownload#windows).

I've reproduced the problem on Windows 8.1 with Node.js 0.12.2 : I've got exactly the same error message as you.
I've downgraded Node.js to version 0.10.36 and then `npm install` and it works (only a few warnings)!
